### PR TITLE
Investigate #184 by running on more OSes.

### PR DESCRIPTION
**Pull request by eriknw**
Also, don't show chained/nested exceptions when unnecessary.

### CODE REVIEW

**Comment by eriknw** [comment]
Alright, apparently it's actually important for us to test on different OSes.  This test fixes many tests that were failing on Windows (don't get me started about `np.ldexp` on Windows!).

So, to keep our CI config matrix from exploding, I added a `pytest --randomly` which randomly chooses between blocking and non-blocking, record or not, runslow or not, and mapnumpy or not.  This give us 16 variations, and we run `pytest --randomly` 28 times in CI (so, on average, this will test 13.5 of 16 configurations for each set of runs).  Be on the lookout for intermittent test failures.  I also explicitly list out the matrix config options to run in CI.

The other bit of hygiene that this PR does is it adds `raise ... from None` more often so we don't chain exceptions when there's no value in doing so.

Unfortunately, I was unable to reproduce the segfault from #184, which was the impetus for this PR.

**Comment by ParticularMiner** [comment]
Just to confirm: this latest merge has not fixed the segfault in #184.

**Comment by eriknw** [comment]
> Just to confirm: this latest merge has not fixed the segfault in https://github.com/metagraph-dev/grblas/issues/184.

Probably not.  I didn't do anything that is specifically meant to try to fix it.  When you run tests locally, do you segfault?

**Comment by ParticularMiner** [comment]
Interestingly, I do not segfault when I run tests locally.  But sometimes, when using the debugger, a segfault does prop up.  Whether a segfault occurs or not under the debugger appears to be arbitrary.  This is quite weird and I'll be very interested to know what could cause such behavior.

**Pull request merged**
